name: Playwright tests
on:
  pull_request:
  push:
    branches: [main, playwright-next]

jobs:
  playwright-tests:
    name: Playwright tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        playwright-version: [1.34.x, 1.38.x, 1.44.x, next]
        example:
          - create-react-app-typescript
          - nextjs-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn --immutable
      - run: yarn run build
      - run: yarn add --dev "replayio@workspace:^"
      - run: npx --no replayio install
      - run: yarn set resolution "@playwright/test@*" ${{ matrix.playwright-version }}
      - run: yarn test
        working-directory: examples/${{ matrix.example }}
      - run: node test/upload-and-check-recording.js
        working-directory: examples/${{ matrix.example }}
        env:
          REPLAY_API_KEY: ${{ secrets.RECORD_REPLAY_API_KEY }}
